### ISSUE TITLE
VIM - editor de textos

### ISSUE THREAD

**Issue by PauloSilva92** [Webschool-io/be-mean-hangouts#11]
Hangout sobre passos básicos no editor de textos superpoderoso VIM

-modos
-comandos básicos
-customização
-instalação de plugins

17/02/2015 á noite

link do hangout 
https://plus.google.com/events/cjpk3piu0bn7acd7b63h46eao2c

**Comment by Pompeu** [comment]
Opa..
+1

**Comment by lucasduarte** [comment]
To garrado.
+1

**Comment by hc3** [comment]
massa agora coloca para ou pela manhã ou após as 20:00 por favor

**Comment by kurybr** [comment]
+1

**Comment by davidsonsns** [comment]
Boa man
+1

**Comment by manzettidenis** [comment]
boa, qual o horário !?
+1

**Comment by lucasduarte** [comment]
cade ue? ja passou da hora

**Comment by PauloSilva92** [comment]
As 22 vai ser

**Comment by lucasduarte** [comment]
beleza

**Comment by PauloSilva92** [comment]
no hangout eu  vou priorizar quem tem experiencia com o VIM, então se alguem tiver experiencia fala comigo que eu abro vaga pra entrar, quem não conseguir entrar assiste pelo youtube 
https://www.youtube.com/watch?v=2rXaXSE2EG0

**Comment by PauloSilva92** [comment]
começou

**Comment by manzettidenis** [comment]
Quem não conseguir entrar, pode assistir pelo Youtube:
http://www.youtube.com/watch?v=bl-OZdhZZ1A
