### ISSUE TITLE
Pré - Processadores

### ISSUE THREAD

**Issue by kurybr** [Webschool-io/be-mean-hangouts#8]
Um Hangout sobre a importancia de utilizar Préprocessadores no CSS, como Stylus, Sass, Less entre outros..

Além da importancia, mostrar quais as vantagens no código final

**Comment by PauloSilva92** [comment]
quero

**Comment by filipe1309** [comment]
+1

**Comment by hc3** [comment]
+1

**Comment by omarkdev** [comment]
Vai ter curso disso já!

**Comment by IgorHalfeld** [comment]
@omarkdev no curso vai ter só stylus, não? nesse Hangout seria uma pegada mais pro sass ou algo assim

**Comment by omarkdev** [comment]
@Halfeld vai ter curso de Stylus (meu), SASS, LESS e PostCSS.

**Comment by IgorHalfeld** [comment]
@omarkdev certo, o que eu não entendi então foi ter um Hangout de Gulp vs Grunt... se no curso vai ter no modulo de front-end....

**Comment by kurybr** [comment]
@Halfeld  Mano, os Hangouts não são relacionados ao curso, são só o pessoal querendo compartilhar conhecimento ou bater um papo sobre alguma tecnologia, não necessáriamente precisa ter um material, Por isso as ideias vão surgindo, de que tipos de hangout poderiam ser feitos.

é algo sem um "compromisso" fechado, é mais uma "pró atividade" do pessoal em compartilhar conhecimento

**Comment by kurybr** [comment]
Fizemos por exemplo um Hangout final de semana, sobre MongoDB, esse foi só para estudarmos ( como se fosse reunir a turma na "faculdade" para estudar sobre a matéria ) porém foi uma iniciativa nossa, por que estavamos com tempo e tal.. 

Deu pra entender ? 

(Mas outro exemplo, eu fiz um Hangout para ajudar a galera que tinha dificuldade em começar no CSS )

**Comment by IgorHalfeld** [comment]
@kurybr Ahh saquei mano, show de bola, tamo junto !

**Comment by suissa** [comment]
Na verdade o deles não serão hangouts, serão aulas gravadas que farão parte do conteudo do Be MEAN do modulo de frontend.

Blz?
